# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, verbose_name='\u4e3b\u673a\u7ec4')),
                ('addip', models.CharField(max_length=20, unique=True, verbose_name='\u4e3b\u673aip')),
                ('status', models.CharField(default='0', max_length=5, verbose_name='\u4e3b\u673a\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ba1\u7406\u8868',
            },
        ),
        migrations.CreateModel(
            name='SelectHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectip', models.CharField(max_length=20, unique=True, verbose_name='\u9009\u62e9IP')),
                ('selectgroup', models.CharField(default='', max_length=20, verbose_name='\u9009\u62e9\u4e3b\u673a\u7ec4')),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u4e3b\u673a\u8868',
            },
        ),
    ]
