# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0003_tuxedoservice_tuxedosingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='area',
            field=models.IntegerField(choices=[(1, '\u4ea6\u5e84'), (2, '\u4e30\u53f0')], default=1, verbose_name='\u6240\u5c5e\u5730\u533a'),
        ),
    ]
