# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0005_auto_20170905_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuxedosingle',
            name='single_group',
            field=models.CharField(choices=[('chmap', '\u8054\u673a\u670d\u52a1'), ('chcom', '\u6570\u636e\u4ee3\u7406'), ('chdb', '\u6570\u636e\u5904\u7406')], default='chmap', max_length=20, verbose_name='\u4e3b\u673a\u7ec4'),
        ),
        migrations.AlterField(
            model_name='tuxedosingle',
            name='single_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u8fdb\u7a0b\u540d\u79f0'),
        ),
    ]
