# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0006_auto_20170905_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redis_ip', models.GenericIPAddressField(null=True, protocol='ipv4', unique=True)),
                ('redis_name', models.CharField(blank=True, max_length=20, verbose_name='redis\u540d\u79f0')),
                ('redis_port', models.CharField(blank=True, max_length=20, verbose_name='redis \u7aef\u53e3')),
                ('redis_desc', models.TextField(blank=True, default='', verbose_name='redis \u529f\u80fd\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': 'REDIS\u4fe1\u606f\u8868',
                'verbose_name_plural': 'REDIS\u4fe1\u606f\u8868',
            },
        ),
    ]
